name: build
on:
  pull_request:
# testaaaaaaaaaaaaazzzzaaaa
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        key: docker-layer-caching-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('docker-compose.yml') }}
        continue-on-error: true

      - run: docker-compose -f docker-compose.yml up -d

      - run: docker-compose run --rm app bundle install

  rspec:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: test
        continue-on-error: true

      - run: docker-compose run --rm app rails db:create RAILS_ENV=test

      - run: docker-compose run --rm app rails db:migrate RAILS_ENV=test
      - run: docker-compose run --rm app bundle exec rspec