name: build
on:
  pull_request:
# testaaaaaaaaaaaaazzzzaaaa
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: docker-layer-caching-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('docker-compose.yml') }}
        continue-on-error: true

      - run: docker-compose -f docker-compose.yml up -d

      - run: docker-compose run --rm app bundle install

      - name: Merge to develop branch
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: git checkout develop && git merge --no-ff ${{ github.event.pull_request.head.ref }} && git push

      - name: Run RSpec on develop branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: bundle exec rspec

      - name: Merge to release branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: git checkout release && git merge --no-ff develop && git push

      - name: Run RSpec on release branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: bundle exec rspec

  rspec:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        with:
          key: test
        continue-on-error: true

      - run: docker-compose run --rm app rails db:create RAILS_ENV=test

      - run: docker-compose run --rm app rails db:migrate RAILS_ENV=test
      - run: docker-compose run --rm app bundle exec rspec