name: buildpush
on:
  push:
    branches:
      - develop
# testaaaaaaaaaaaaagggg
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.11
        key: docker-layer-caching-${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('docker-compose.yml') }}
        continue-on-error: true

      - run: docker-compose -f docker-compose.yml up -d

      - run: docker-compose run --rm app bundle install